apiVersion: v1
kind: Secret
metadata:
  name: nyaymadad-secrets
  namespace: nyaymadad
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/nyaymadad?retryWrites=true&w=majority"
  REDIS_URL: "redis://nyaymadad-redis-service:6379"
  GEMINI_API_KEY: "<vault_injected_gemini_api_key>"
  CLERK_SECRET_KEY: "<vault_injected_clerk_secret_key>"
